In [1]:
!git clone https://github.com/gokulg02/DEXBOT-CV-workshop

fatal: destination path 'DEXBOT-CV-workshop' already exists and is not an empty directory.


Importing Numpy library

In [2]:
import numpy as np

***Declaring a numpy array***

In [3]:
a = np.array([1,2,3])
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print("Shape:",a.shape)
print("Array:")
print(a)

Shape: (3,)
Array:
[1 2 3]


In [5]:
print("Shape:",b.shape)
print("Array:")
print(b)

Shape: (3, 4)
Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


***Indexing*** 

*Obtaining the element 7* 

In [6]:
b[1,2]

7

**Printing the array [[2,3],[6,7]] from b.**

In [7]:
b[0:2,1:3]

array([[2, 3],
       [6, 7]])

**Reshaping**

*Reshaping b into array of shape (4,3).*

In [8]:
b.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**Efficiency of numpy arrays**

In [9]:
import time
x=[]
for i in range(10000000):
    x.append(i)
    
start = time.time()
for i in range(10000000):
    x[i] += 2

print("Time taken:",time.time()-start," s")

Time taken: 1.478792667388916  s


In [10]:
y = np.array(x)

start = time.time()

y += 2

print("Time taken:",time.time()-start," s")

Time taken: 0.0  s


**Reading and displaying images usign openCV**

In [11]:
import cv2

In [16]:
a = cv2.imread(r"data\lena.png")

In [13]:
cv2.imshow("a",a)
cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:971: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


In [14]:
a

In [ ]:
type(a)

In [ ]:
a.shape

**Displaying image using matplotlib**

In [18]:
import matplotlib.pyplot as plt

In [19]:
plt.imshow(a[:,:,::-1])

TypeError: 'NoneType' object is not subscriptable

**RGB Representation**

In [ ]:
img = cv2.imread(r"data\rubik.png")
plt.imshow(img[:,:,::-1])

In [ ]:
blue_img = np.zeros(img.shape)
blue_img[:,:,0] = img[:,:,0]
f, ax = plt.subplots(2,figsize=(10, 10))
ax[0].imshow(blue_img[:,:,::-1])
ax[1].imshow(img[:,:,::-1])

In [ ]:
green_img = np.zeros(img.shape)
green_img[:,:,1] = img[:,:,1]
f, ax = plt.subplots(2,figsize=(10, 10))
ax[0].imshow(green_img[:,:,::-1])
ax[1].imshow(img[:,:,::-1])

In [ ]:
red_img = np.zeros(img.shape)
red_img[:,:,2] = img[:,:,2]
f, ax = plt.subplots(2,figsize=(10, 10))
ax[0].imshow(red_img[:,:,::-1])
ax[1].imshow(img[:,:,::-1])

**HSV color space**

In [ ]:
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
f, ax = plt.subplots(2,2,figsize=(10, 10))
ax[0,0].imshow(img[:,:,::-1])
h, s, v = cv2.split(hsv)
ax[0,1].imshow(h,cmap='gray')
ax[1,0].imshow(s,cmap='gray')
ax[1,1].imshow(v,cmap='gray')
ax[0, 0].set_title("Original")
ax[0, 1].set_title("Hue")
ax[1, 0].set_title("Saturation")
ax[1, 1].set_title("Value")

**Convert RGB --> Grayscale**

In [ ]:
img=cv2.imread('data/butterfly.jpg')
plt.imshow(img[:,:,::-1])

In [ ]:
grayImg = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
plt.imshow(grayImg, cmap='gray')

In [ ]:
rgb = cv2.cvtColor(grayImg,cv2.COLOR_GRAY2RGB)
cv2.imshow("RGB", rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()

**Brightening and Darkening**

In [ ]:
img = cv2.imread('data/robin.jpeg')
plt.imshow(img[:,:,::-1])

In [ ]:
illum = np.ones(img.shape, dtype="uint8") * 75
brightenedImg=cv2.add(img,illum)
plt.imshow(brightenedImg[:,:,::-1])

In [ ]:
darkenedImg=cv2.subtract(img, illum)
plt.imshow(darkenedImg[:,:,::-1])

**Translation**

In [ ]:
img = cv2.imread('data/gull.jpg') 
height,width = img.shape[:2]
print(img.shape[:2])
plt.imshow(img[:,:,::-1])

In [ ]:
newHeight, newWidth = height/4, width/4
translationMatrix = np.float32([[1,0,newWidth],[0,1,newHeight]])
translatedImg=cv2.warpAffine(img,translationMatrix,(width,height))
print(translationMatrix)
plt.imshow(translatedImg[:,:,::-1])

**Rotation**

In [21]:
rotationMatrix=cv2.getRotationMatrix2D((width/2, height/2),180,1)
rotatedImg=cv2.warpAffine(img,rotationMatrix,(width,height))
print(rotationMatrix)
plt.imshow(rotatedImg[:,:,::-1])

NameError: name 'width' is not defined

**Interpolation**

In [ ]:
plt.imshow(img[:,:,::-1])
print(img.shape)

In [ ]:
downScaledImg = cv2.resize(img,None,fx = 0.75,fy = 0.75)
plt.imshow(downScaledImg[:,:,::-1])
print(downScaledImg.shape)

In [ ]:
upScaledImg = cv2.resize(img,None,fx = 2,fy = 2,interpolation = cv2.INTER_CUBIC)
plt.imshow(upScaledImg[:,:,::-1])
print(upScaledImg.shape)

In [ ]:
resizedImg = cv2.resize(img,(200,300),interpolation = cv2.INTER_AREA)
plt.imshow(resizedImg[:,:,::-1])
print(resizedImg.shape)

**Cropping**

In [ ]:
croppedImg = img[200:600, 1200:1500]
plt.imshow(croppedImg[:,:,::-1])
print(croppedImg.shape)

**Perspective Transform**

In [ ]:
img = cv2.imread('data/thresh.png')
rows,cols,ch = img.shape
print(rows, cols, ch)
plt.imshow(img[:,:,::-1])

In [ ]:
source = np.float32([[50,55],[356,45],[25,352],[376,355]])
destination = np.float32([[0,0],[300,0],[0,300],[300,300]])
transformMatrix = cv2.getPerspectiveTransform(source, destination)
transformedImg = cv2.warpPerspective(img,transformMatrix,(300,300))
plt.imshow(transformedImg[:,:,::-1])